/*================================================================*/
/* Database name:  GameParadise			                          */
/* DBMS name:      Microsoft SQL Server 2017                      */
/* Created on:     20/12/2017							          */
/* Made by:        Martijn de Geus								  */
/* Purpose:        Views for application						  */
/*================================================================*/

USE GAMEPARADISE
GO

-- Creëer view voor de omzet van januari 2015 (alleen verhuurovereenkomsten die niet geannuleerd zijn).
DROP VIEW VIEW_OMZET_JAN_2015
GO

CREATE VIEW VIEW_OMZET_JAN_2015 AS
SELECT 
	SUM(VERHUURTOTAAL) AS OMZET_VERHUUR, SUM(VERKOOPTOTAAL) AS OMZET_VERKOOP, SUM(VERHUURTOTAAL) + SUM(VERKOOPTOTAAL) AS TOTALE_OMZET
FROM
	(
		SELECT KL.EMAILADRES, HU.STARTDATUM, HU.EINDDATUM, DATEDIFF(day, HU.STARTDATUM, HU.EINDDATUM) * A1.PRIJS_PER_D AS VERHUURTOTAAL
		FROM KLANT KL
		LEFT JOIN HUUROVEREENKOMST HU ON KL.EMAILADRES = HU.EMAILADRES
		LEFT JOIN ARTIKELENVERHUUR AH ON HU.STARTDATUM = AH.STARTDATUM AND HU.EMAILADRES = AH.EMAILADRES
		LEFT JOIN ARTIKEL A1 ON AH.BARCODE = A1.BARCODE
		WHERE
			MONTH(HU.STARTDATUM) = 1 AND YEAR(HU.STARTDATUM) = 2015
			AND HU.HUURSTATUS <> 'GEANNULEERD'
	) H
	,
	(
		SELECT KL.EMAILADRES, VK.DATUM, A2.PRIJS AS VERKOOPTOTAAL
		FROM KLANT KL
		LEFT JOIN VERKOOPOVEREENKOMST VK ON KL.EMAILADRES = VK.EMAILADRES
		LEFT JOIN ARTIKELENVERKOOP AV ON VK.DATUM = AV.DATUM AND VK.EMAILADRES = AV.EMAILADRES
		LEFT JOIN ARTIKEL A2 ON AV.BARCODE = A2.BARCODE
		WHERE
			MONTH(VK.DATUM) = 1 AND YEAR(VK.DATUM) = 2015
	) K;

-- Creëer view voor het meest verhuurde spel (absoluut aantal keren verhuurd op basis van titel, niet aantal dagen?).
DROP VIEW VIEW_MEEST_GEHUURD_SPEL
GO

CREATE VIEW VIEW_MEEST_GEHUURD_SPEL AS
SELECT TOP 1 WITH TIES
	AR.TITEL, COUNT(AR.BARCODE) AS KEREN_VERHUURD
FROM HUUROVEREENKOMST HU
LEFT JOIN ARTIKELENVERHUUR AV ON HU.EMAILADRES = AV.EMAILADRES
INNER JOIN ARTIKEL AR ON AV.BARCODE = AR.BARCODE
WHERE AR.SPEL_OF_CONSOLE = 'SPEL' AND HU.HUURSTATUS <> 'GEANNULEERD'
GROUP BY AR.TITEL
ORDER BY COUNT(AR.BARCODE) DESC;


-- Creëer view voor huurovereenkomst met de hoogste omzet (?).
DROP VIEW VIEW_HUUROVEREENKOMST_MAX
GO

CREATE VIEW VIEW_HUUROVEREENKOMST_MAX AS
SELECT TOP 1 WITH TIES
	HU.EMAILADRES, HU.STARTDATUM, HU.EINDDATUM, SUM(AR.PRIJS_PER_D * DATEDIFF(day, HU.STARTDATUM, HU.EINDDATUM)) AS VERHUURTOTAAL
FROM HUUROVEREENKOMST HU
INNER JOIN ARTIKELENVERHUUR AV ON HU.EMAILADRES = AV.EMAILADRES AND HU.STARTDATUM = AV.STARTDATUM
INNER JOIN ARTIKEL AR ON AV.BARCODE = AR.BARCODE
GROUP BY HU.EMAILADRES, HU.STARTDATUM, HU.EINDDATUM
ORDER BY SUM(AR.PRIJS_PER_D * DATEDIFF(day, HU.STARTDATUM, HU.EINDDATUM)) DESC;


-- Creëer view voor totale schade in 2016 (?).
DROP VIEW VIEW_SCHADE_MAX_2016
GO

CREATE VIEW VIEW_SCHADE_MAX_2016 AS
SELECT 
	SUM(RE.KOSTEN) AS TOTALE_SCHADE
FROM REPARATIE RE
WHERE YEAR(RE.STARTDATUM) = 2016;


-- Creëer view voor consoles met meeste schades (Alle beschadigde consoles aflopend gesorteerd op TOTAAL_SCHADES?).
DROP VIEW VIEW_MEEST_BESCHADIGD
GO

CREATE VIEW VIEW_MEEST_BESCHADIGD AS
SELECT 
	RE.BARCODE, AR.MERK, AR.TYPE, SUM(RE.KOSTEN) AS TOTAAL_SCHADES, AR.PRIJS
FROM REPARATIE RE
INNER JOIN ARTIKEL AR ON RE.BARCODE = AR.BARCODE
GROUP BY RE.BARCODE, AR.MERK, AR.TYPE, AR.PRIJS
ORDER BY SUM(RE.KOSTEN) DESC;

